version: '3.8'
services:
  sqlserver:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  db-migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./seed-data:/scripts
    environment:
      - ConnectionString=Server=sqlserver;Database=pubs;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    command: ["grate", "--connectionstring", "Server=sqlserver;Database=pubs;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True", "--files", "/scripts"]

volumes:
  sqldata:
    driver: local 